spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}

jwt:
  secret: ${JWT_SECRET}
